### PR TITLE
Add missing asserts

### PR DESCRIPTION
**Pull request by padwasabimasala**
Added missing assert to automated tests for command handlers

At least they appear to be missing. There's a check on the instance of each message created, but no assert on the value the check returns.

### CODE REVIEW

**Comment by ntl** [comment]
The lines of code in question aren't meant to have assertions. They are using the writer substitute's interface for getting a particular message that the writer substitute has written. After getting the message that the test files expect was written, there is a test that the message retrieved from the writer substitute isn't `nil`. Thus, the assertions added by this pull request seem to be redundant.

Does that make sense?

**Comment by joshuaflanagan** [comment]
It might help to recognize that the `do...end` block represents a predicate. The `event.instance_of?` provides the return value for the predicate, to determine the message to select. The block is not intended to perform a series of actions (like assert).

**Comment by ntl** [comment]
Indeed, that's a much better explanation, thanks @joshuaflanagan ! I was kind of feeling the typist's equivalent of tongue-tied when I wrote my reply.

**Comment by padwasabimasala** [comment]
I see. one_message returns the first message once the block evaluates to true. I misunderstood the intent of the block.

Thanks for the explanation. Closing

**Pull request closed without merging**
